services:
  beacon:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: beacon.dev
    container_name: beacon_dev
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./apps/server:/app/apps/server
      - ./Cargo.toml:/app/Cargo.toml
    env_file:
      - .env.dev
