FROM rust:1.97.1
 
WORKDIR /app

COPY Cargo.toml Cargo.lock ./
COPY src ./src
COPY entrypoint.dev.sh /entrypoint.dev.sh
RUN chmod +x /entrypoint.dev.sh
 
EXPOSE 5000
ENTRYPOINT [ "/entrypoint.dev.sh" ]
