export const InputType = {
  TEXT: 'text',
  PASSWORD: 'password',
  FILE: 'file',
  HIDDEN: 'hidden',
  RADIO: 'radio',
  DATE: 'date',
  CHECKBOX: 'checkbox',
  COLOR: 'color',
  EMAIL: 'email',
  WEEK: 'week',
  URL: 'url',
  TIME: 'time',
  TEL: 'tel',
  SUBMIT: 'submit',
  SEARCH: 'search',
  RESET: 'reset',
  RANGE: 'range',
  NUMBER: 'number',
  MONTH: 'month',
  IMAGE: 'image',
  DATETIME_LOCAL: 'datetime-local',
  BUTTON: 'button',
} as const;

